version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    env_file:
      - .env.database
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - wps

  web:
    build: .
    ports:
      - 8000:80
    volumes:
      - ./:/app
    depends_on:
      - db
    networks:
      - wps

networks:
  wps:
